### ISSUE TITLE
The width and height of a text

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/Chaldene#107]
Conversion between the font style (px) and width of the shape

**Comment by Max-ChenFei** [comment]
```
fillText(text, x, y)
```
x: The x-axis coordinate of the point at which to begin drawing the text, in pixels.

```
CanvasRenderingContext2D.font
```
A string parsed as CSS [font](https://developer.mozilla.org/en-US/docs/Web/CSS/font) value. The default font is 10px sans-serif.

**Comment by Max-ChenFei** [comment]
https://stackoverflow.com/questions/26437176/resize-text-as-rectangle-resizes-in-canvas-html5

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText

**Comment by drcd1** [comment]
To get the width of a string, we can either use measureText, or look at the cached .cumWidths (cumulative widths) variable in the Textbox. For the height, I-m currently using the font size as the line height, but this is not exact. Ideally, we would use TextMetrics.fontBoundingBoxAscent and TextMetrics.fontBoundingBoxDescent (https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics/fontBoundingBoxAscent), but these are no longer suppoorted by default in firefox. An alternative would be to measure a text containing the highest and lowest character ("Hg"), but this is also not exact.
