### ISSUE TITLE
Margin between menu bar and first level tab

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/Chaldene#173]
![image](https://user-images.githubusercontent.com/28513798/208064573-16cedc77-43fc-429a-8cc0-b3a7b5c82038.png)

**Comment by drcd1** [comment]
Should it be bigger or smaller?

**Comment by drcd1** [comment]
![imagem](https://user-images.githubusercontent.com/22733172/208087606-2f92c715-5eb9-4f78-834b-56ce4f95dbac.png)
this is their original example. You can see that unselected tabs are supposed to be smaller in size.

**Comment by Max-ChenFei** [comment]
The first is from us while the second is from an official example. You can see the different marked.
![image](https://user-images.githubusercontent.com/28513798/208095684-25ef4575-bcc9-4345-8376-093b12e01e4d.png)
![image](https://user-images.githubusercontent.com/28513798/208095784-794f18d8-c218-4421-a2b8-453066a3fbd8.png)

The margin between dock and menu

**Comment by Max-ChenFei** [comment]
BoxPanel css issue
