### ISSUE TITLE
Maximize and unmaximize the canvas

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/Chaldene#18]
There will two buttons at the right top corner of the canvas. We can maximize the canvas to full screen when clicking on the button and restore it to normal size when clicking the other button.

**Comment by Max-ChenFei** [comment]
It is better to specify your canvas dimensions by setting the width and height attributes directly on the <canvas> elements, either directly in the HTML or by using JavaScript, not using CSS, which will make the image distorted.

**Comment by Max-ChenFei** [comment]
reference:https://github.com/jagenjo/litegraph.js/blob/376f6434e87a04c309ed55620726f6e9b733c1a9/src/litegraph-editor.js#L189-L198

**Comment by Max-ChenFei** [comment]
`drawButton` could be helpful.

**Comment by Max-ChenFei** [comment]
@drcd1 Hi Duarte, I think this tool (zoom in, zoom out, reset) is better than minimap? what's your opinion?
![image](https://user-images.githubusercontent.com/28513798/181249296-40caa79e-cebc-43cb-8e31-f52d833ccf97.png)
We can just create two buttons with text （- and +）

**Comment by drcd1** [comment]
I think both are necessary. A mini-map can provide quick navigation plus context, while users work on smaller details. We already have zoom in and zoom out options (but no reset). Maybe it would be good to provide a UI like the one you suggest, in addition to hotkeys.

**Comment by Max-ChenFei** [comment]
> I think both are necessary. A mini-map can provide quick navigation plus context, while users work on smaller details. We already have zoom in and zoom out options (but no reset). Maybe it would be good to provide a UI like the one you suggest, in addition to hotkeys.

Yes, I think such zoom tool is easy to implement compared with the minimap.  We already have zoom in and zoom out functionality. For minimap, we should show the all content and current visible viewport. Add also we should add some navigation like mouse move event. In addition, the canvas is unlimited in size, the minimap should also be auto-resized. A little complicated.

By the way, I see the zoom tool in some visual programming environments, but no minimap. The minimap is popular in games that have the limited-size scene.

**Comment by drcd1** [comment]
I was thinking of a minimap similar to the one which is very common in text editors and IDE's for usual (non-visual) programming environments.

I should have an initial commit with the mini-map tomorrow.

**Comment by drcd1** [comment]
Note: when maximizing/minimizing the canvas, we can't use the browser/JS functionality (`element.requestFullscreen()`). This is because the context menu is drawn using HTML/CSS, and, if we make the canvas fullscreen, it will draw over the context menu. Instead, I will make the canvas draw over the whole jupyter notebook when it is fullscreen.
