### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/Chaldene#24]
* redu
* undo
*  expand
*  collapse

**Comment by drcd1** [comment]
Shouldn't "redo" and "undo" be a part of the main UI and not a context menu? In most UI's I've seen, undo and redo are accessed through:
 - a button in the "edit" tab/drop down menu on the top bar
 - hotkeys (Ctrl-Z and Ctrl-Y)

I've never seen them accessed through a context menu.

**Comment by Max-ChenFei** [comment]
> Shouldn't "redo" and "undo" be a part of the main UI and not a context menu? In most UI's I've seen, undo and redo are accessed through:
> 
> * a button in the "edit" tab/drop down menu on the top bar
> * hotkeys (Ctrl-Z and Ctrl-Y)
> 
> I've never seen them accessed through a context menu.

Currently, we don't have any main menu, so just add to the context menu instead first. If we just have few menus, like redo undo, I think it is not worth introducing the main menu.

**Comment by Max-ChenFei** [comment]
> Shouldn't "redo" and "undo" be a part of the main UI and not a context menu? In most UI's I've seen, undo and redo are accessed through:
> 
> * a button in the "edit" tab/drop down menu on the top bar
> * hotkeys (Ctrl-Z and Ctrl-Y)
> 
> I've never seen them accessed through a context menu.

I think low complexity, low risk, and less implementation are the first goals.  We should compare which way is lower complexity and lower risk. Maybe in the future, if we have more menus or actions, I think it is low complex to add the main UI. but now just two actions.

**Comment by Max-ChenFei** [comment]
> redu/ undo 
> reference: https://github.com/jagenjo/litegraph.js/pull/271/commits/624269776add06277172ba107531920660d9e096

**Comment by Max-ChenFei** [comment]
`getNodeMenuOptions` for the node

**Comment by Max-ChenFei** [comment]
For different objects (nodes, slots, connectors) on the canvas, there will be different context menus. We use `lumino`  GUI framework.
