### ISSUE TITLE
Rename LGraphGroup to Comment and can resize from the any edge 

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/Chaldene#27]

**Comment by drcd1** [comment]
LGraphGroup isn't just a "comment", though. It also provides the functionality to move every "grouped" component at the same time, although I find the way it works to be a bit counter intuitive (if you move a group over other objects, they will become appended to the group). I would suggest removing or altering this functionality.

**Comment by Max-ChenFei** [comment]
> LGraphGroup isn't just a "comment", though. It also provides the functionality to move every "grouped" component at the same time, although I find the way it works to be a bit counter intuitive (if you move a group over other objects, they will become appended to the group). I would suggest removing or altering this functionality.

In Unreal Engine Blueprint, the comment node also provides the functionality to move every "grouped" component at the same time. for example:
![34](https://user-images.githubusercontent.com/28513798/181295088-e198bf48-f4b4-4012-8770-44e8bd61f9db.gif).

I think it is not a big issue some nodes that overlap with a comment node can be moved along with that comment node. I think it is just a side effect.  The main reason is when some node is overlapped with a comment node, means the comment is also applied to this node.  All the nodes inside the comment component to some degree imply the scope of this comment. Secondly, I don't like the group this term because this group is not very common in conventional textual programming and I want to keep low learning costs when transferring to a visual programming environment. The comment is commonly used in normal programming.

**Comment by Max-ChenFei** [comment]
Or we can group the nodes that are entailed in the comment node, not partially.
