### ISSUE TITLE
Change mouse button for Marquee tool and Scene Pan 

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/Chaldene#28]
Currently, the graph pan is via holding the left mouse button and the Marquee tool is via holding the left mouse button and pressing the Ctrl key.
Please let graph pan trigger via **right** mouse button hold and the Marquee tool via **left** mouse button hold.

**Comment by drcd1** [comment]
Fixed by https://github.com/Max-ChenFei/Chaldene/commit/e880722c93794bdff23d7100c5c3e0aed67ce413, https://github.com/Max-ChenFei/Chaldene/commit/730a9fc4639574513efd420dfd1405de14827e9a and https://github.com/Max-ChenFei/Chaldene/commit/5fad98ad48f2a2cdc7a8a92cd536e25590f45430
