### ISSUE TITLE
Pointers (touch) events

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/Chaldene#30]
Pinch zoom gestures https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures

**Comment by Max-ChenFei** [comment]
Pinch zoom gestures https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures

**Comment by drcd1** [comment]
Just adding a few here so we remember later:

- Ctrl + LMB allows for box selection and multiple selections.
- Shift + LMB allows for multiple selections.
