### ISSUE TITLE
Remove aliasing from background grid

### ISSUE THREAD

**Issue by drcd1** [Max-ChenFei/Chaldene#33]
Improve the rendering of the background grid to take into account sub-pixel lines.
When zoomed out enough, you can see that some lines are missing, in an uneven way.

![imagem](https://user-images.githubusercontent.com/22733172/181588582-5b826129-fbcf-4d8f-aec4-39549fe2efae.png)

**Comment by Max-ChenFei** [comment]
The background is rendered via `canvas.setPattern(image, "repeat")`. 
When zooming out, we just scale the canvas. we should also subdivide the basic background image. 

https://user-images.githubusercontent.com/28513798/181638305-025ef4c8-e05a-47f9-b1f7-d20cef7bd18f.mp4

**Comment by Max-ChenFei** [comment]
`imageSmoothingEnabled = true`
