### ISSUE TITLE
Move the zoom widget to the right bottom of the canvas

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/Chaldene#40]
![image](https://user-images.githubusercontent.com/28513798/187150180-eefbaa26-9ec2-4f92-a479-c29b9fa3d969.png)

**Comment by drcd1** [comment]
Closed by [ee480a](https://github.com/Max-ChenFei/Chaldene/commit/ee480aed1d36296ed2a70cd8a48e173a3f97226b).
![imagem](https://user-images.githubusercontent.com/22733172/187175871-9477d0b4-85c0-4adb-b4eb-a4d090cc0afc.png)
