### ISSUE TITLE
Record hovered object at each frame

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/Chaldene#51]
I check the commits and basic understand your idea of using hovered objects to replace `getNodeInPose`.

Your idea is 
1. add nodes and slots to `hoverables`  in `drawNodes`  function.
2. for each frame, compute the hovered objects
3. reference this hovered object in other places like mouse events function.

**Comment by Max-ChenFei** [comment]
Q1:  Where the `node` comes from?
https://github.com/Max-ChenFei/Chaldene/commit/45a739c3849bf48fbeddb11157955346bd4ce944#r85898205

**Comment by Max-ChenFei** [comment]
Q2: Should we treat slot and node equally and put them into one list? 
* The slots or other child components are in the node item. If we test them in the loop, we will break this composition relationship. Some events will miss. For example, The node hovered event should be triggered at first and then test other child components.
* If the node has not hovered, we don't need to test the slots inside this node.

**Comment by drcd1** [comment]
We should treat them equally. Each "hovered" object is not exactly the object itself, but a proxy that contains references. For instance, when hovering over a slot, we store a reference to the parent node as well as the slot. This is not only simpler but also more useful: if a node is composed of elements that go outside of the node rectangle (see the way blender styles node sockets - they exceed a bit the margins of the node), then we just need to detect the socket to know we are hovering over the node.

Another rationale for this design is that it keeps the "collision detection" as simple as possible with a clear abstraction layer. Only simple shapes, and no knowledge of type or composition.

**Comment by Max-ChenFei** [comment]
Q3:  This piece of code is used at least two times. It is better to put it into one function with a good name.
```
        var node = null;
        if(this.hovered && this.hovered.node){
            node = this.hovered.node;
        }
```

**Comment by Max-ChenFei** [comment]
> If a node is composed of elements that go outside of the node rectangle (see the way blender styles node sockets - they exceed a bit the margins of the node), then we just need to detect the socket to know we are hovering over the node.

I think you are right. I did not consider the socket outside of the bounding box of the node.

> Another rationale for this design is that it keeps the "collision detection" as simple as possible with a clear abstraction layer. Only simple shapes, and no knowledge of type or composition.

I agree we should keep collision detection as simple as possible and only take care of basic shapes without the need to know any type or node.
