### ISSUE TITLE
Collapse is not in context menu

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/Chaldene#54]

**Comment by drcd1** [comment]
Context menu, as a whole, is not working in the "development" branch (i.e.: context menu is always as if you're clicking over the canvas, not a node or other specific object). It works in the "refactoring_collision_detection" branch. I will check to see when the regression happened.

**Comment by drcd1** [comment]
This was caused by 2565faf3ad3db289d3ac101587e22c501abe60a2, fixed in "refactoring_collision_detection" by a7813a581ad4de94ad6a81dbc1d14e01570d8c73
