### ISSUE TITLE
User Actions

### ISSUE THREAD

**Issue by drcd1** [Max-ChenFei/Chaldene#59]
This issue provides a checklist for all the actions the users can take, and the objects they can interact with.

## Interactables:
  - Node
  - Node Slot
  - Background (canvas)
  - Minimap

### Selection
 - [x] Single Select Node: LMB up on Node or Node Component
 - [x] Multiple selections: Select something while holding the CTRL key
 - [x] Marquee Selection: Hold the LMB button over the background and move the mouse to draw a rectangle, all the nodes inside this rectangle will be selected. Shift key for add, CTRL for toggle,
  - [x] When selecting multiple nodes, LMB Click to select this node. Shift key for add, CTRL for toggle, no key will cancel the selection before 
  - [x] Unselect Everything: LMB Click on Background
 ### Context Menu: RMB Click 
- [x] Node Context Menu (Delete, Cut, Copy, Duplicate, Break Node Connectors)
- [x] Background Context Menu (Search box, the list of available nodes types)
- [x] Slots Context menu (break the connector)
 ### Nodes
 - [x] Move Node (include comment node): LMB Hold and Drag on Node
 - [x] Resize node: LMB hold and drag over the bottom right corner of a node
 - [x] Resize node:  Mouse Move to the edge of the node, so show se-resize cursor
 - [x] Copies selected nodes: Ctrl-C copies selected nodes and connectors between them.
 - [x] Paste copied nodes: Ctrl-V pastes previously copied nodes, at the position of the cursor.
 - [x] Del key: delete the node

 ### Connectors
 - [x] Create connector split: double click on a connector
 - [x] Move connector split: Select the split with marquee selection. Hold LMB and drag the mouse over the split 
 - [x] Drag new output connector: LMB hold over an output slot
 - [x] Finish a connection: LMB release over and input slot, or a node (to automatically connect to first free compatible slot)
 - [x] change the port to: alt + LMB down
- [x] Remove a connection:  Use context menu or ALT +LMB Click
- [x] reconnect to others slot when holding Ctrl +LMB Click

### Misc
 - [x] scene pan: RMB hold and move on canvas
 - [x] scene zoom: MW
 - [ ] Change view on minimap: LMB click over any point in the minimap to center the view around that point.

**Comment by Max-ChenFei** [comment]
> `I like blender's model.`
More detail?

**Comment by Max-ChenFei** [comment]
> - [ ] Resize node: LMB hold and drag over the bottom right corner of a node

I think for comment node can be resized by people, but others should be automatic, otherwise, we will see the ugly layout of this node, for example, one port is outside of the node.

**Comment by Max-ChenFei** [comment]
> > * [ ]  Resize node: LMB hold and drag over the bottom right corner of a node
> 
> I think for comment node can be resized by people, but others should be automatic, otherwise, we will see the ugly layout of this node, for example, one port is outside of the node.

Let's check how good is this resize. If it is good keep it, otherwise, delete it.

**Comment by Max-ChenFei** [comment]
> For copy and paste node

I suggest doing this when implementing the serialization modules.

**Comment by Max-ChenFei** [comment]
>Create connector split: double click on a connector

How about calling this split `reroute node` inherited from the base node? We can create reroute node and use it or double-click the connector

**Comment by Max-ChenFei** [comment]
Example of Context menu for the canvas. If you cannot preview the video, please download and watch it.

https://user-images.githubusercontent.com/28513798/196034472-563b409f-e30f-4461-8abc-c2a6ac0c3a4e.mp4

**Comment by Max-ChenFei** [comment]
Mouse events summary at https://github.com/Max-ChenFei/Chaldene/wiki/Mouse-Events
