### ISSUE TITLE
The context menu is out of canvas

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/Chaldene#6]
Relocate the context menu at the boundary area to keep it not outside the canvas horizontally.

![image](https://user-images.githubusercontent.com/28513798/179841827-6a85f3f2-7404-497d-ad7a-68eaa3ee7da9.png)

**Comment by drcd1** [comment]
![fix_issue](https://user-images.githubusercontent.com/22733172/180220119-2d66b647-e93c-427c-af0a-3e8f33f8fdc5.png)
The context menu no longer exceeds the canvas horizontally.
