### ISSUE TITLE
MiniMap for the canvas

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/Chaldene#7]
Please add a Minimap for the canvas.

**Comment by Max-ChenFei** [comment]
A reference is:  multiview in the editor https://tamats.com/projects/litegraph/editor/
https://github.com/jagenjo/litegraph.js/blob/376f6434e87a04c309ed55620726f6e9b733c1a9/src/litegraph-editor.js#L270-L281
```
Editor.prototype.addMultiview = function()
{
	var canvas = this.canvas;
	this.graphcanvas.ctx.fillStyle = "black";
	this.graphcanvas.ctx.fillRect(0,0,canvas.width,canvas.height);
	this.graphcanvas.viewport = [0,0,canvas.width*0.5-2,canvas.height];

	var graphcanvas = new LGraphCanvas( canvas, this.graph );
        graphcanvas.background_image = "imgs/grid.png";
        this.graphcanvas2 = graphcanvas;
	this.graphcanvas2.viewport = [canvas.width*0.5,0,canvas.width*0.5,canvas.height];
}
```
set  `graphcanvas.read_only=true`

**Comment by drcd1** [comment]
> A reference is: multiview in the editor

This is probably a better way to implement it. I was already started with this one when I saw your message, but I might change it in a future commit.

**Comment by Max-ChenFei** [comment]
Please move the canvas to the right top corner.

**Comment by Max-ChenFei** [comment]
Disable canvas shadow.

**Comment by drcd1** [comment]
![imagem](https://user-images.githubusercontent.com/22733172/183382771-c0b7afad-1370-4142-b9d6-2529b05acf08.png)
Current status. Still missing the ability to drag/point and click to change the viewport position through the mini-map.

**Comment by drcd1** [comment]
Closed by the pull request. 
![imagem](https://user-images.githubusercontent.com/22733172/186021388-da4f34f6-0402-47a3-8ae3-9eb346778e3b.png)
