### ISSUE TITLE
Arrange nodes does not work

### ISSUE THREAD

**Issue by drcd1** [Max-ChenFei/Chaldene#70]
The "arrange" nodes functionality stopped working as of commit https://github.com/Max-ChenFei/Chaldene/commit/9da82acf8b6285868f77179ec2c1ee931fb58d6d#r87006202 , because it requires the "computeExecutionOrder()" function that was deleted.

**Comment by Max-ChenFei** [comment]
Sorry for that, I will fix this soon.
